EVO-1074 render message names as links to user profiles
Hylozoic/hylo-evo pull request #1091
Opened 2022-01-27 19:33 UTC by Sofacosta

2022-01-27 22:31 UTC, tibetsprague requested changes
This looks great! Only thing is there are some compile/lint issues, make sure to check the running server console to see them before you push, or run yarn lint.

2022-01-27 22:31 UTC, tibetsprague commented on src/routes/Messages/Header/Header.js
> +    const otherParticipants = this.getOthers(this.props.currentUser, participants)
we generally like to pull out all the variables from this.props above, so add currentUser to const { pending } = this.props

2022-01-27 22:31 UTC, tibetsprague commented on src/routes/Messages/Header/Header.js
> +    const otherParticipants = this.getOthers(this.props.currentUser, participants)
and messageThread too

2022-01-28 18:54 UTC, lorenjohnson approved these changes
This looks great! Good work @Sofacosta 👍🏼

2022-01-31 17:56 UTC, Sofacosta commented
It looks like the linter issues have been taken care of @tibetsprague

2022-01-31 17:57 UTC, tibetsprague commented
yup looks good!

2022-01-31 17:58 UTC, tibetsprague approved these changes

2022-02-01 21:58 UTC, merged