Confirm close on create post
Hylozoic/hylo-evo pull request #1097
Opened 2022-02-07 04:15 UTC by antonetteortiz

[#974 Confirm close on Create Modal ](https://github.com/Hylozoic/hylo-evo/issues/974)

Description
--
If user makes any changes to the Create Modal and clicks outside of the window or closes the modal, a confirmation prompt will appear. 

How to Test:
---
- In the create modal, make changes to any of fields.
- Click outside of the window and/or attempt to close the modal.
- Confirmation window will popup, prompting to either return to the create modal or discard post.

2022-02-07 06:20 UTC, tibetsprague requested changes
whoo hoo, looking good! just a couple little suggestions/changes requested, and we can look at the topics thing together

2022-02-07 06:20 UTC, tibetsprague commented on src/components/CreateModal/CreateModal.connector.js
> +    confirmLeaveCreateModal: () => {
this works great, but could be slightly less code and cleaner by just passing an isDirty parameter into closeModal, then you wouldn't need two functions

2022-02-07 06:20 UTC, tibetsprague commented on src/components/CreateModal/CreateModal.js
> +  const checkBeforeClose = () => {
if you pass in isDirty to closeModal then this conditional moves to closeModal

2022-02-07 06:20 UTC, tibetsprague commented on src/components/PostEditor/PostEditor.js
> +      isDirty // prop tracking if form fields were touched from CreateModal
it doesnt look like you are actually using this, why do you need to pass isDirty down to the PostEditor?

2022-02-07 06:20 UTC, tibetsprague commented on src/components/PostEditor/PostEditor.js
> +    this.setIsDirty = props.setIsDirty
you dont need to do this, you can just call this.props.setIsDirty down below

2022-02-07 06:20 UTC, tibetsprague commented on src/components/PostEditor/PostEditor.js
> +      // TODO (Annie): figure out why topic changes don't update isDirty
hmm, strange, we can look at this together

2022-02-07 06:24 UTC, tibetsprague reviewed
oh also we will want to add/tweak our tests to cover the changes, so good opportunity to look at our test code together too

2022-02-07 12:53 UTC, antonetteortiz commented
thanks Tibet, I will work on the change request and connect with you later today to look at topic changes.

2022-02-09 19:35 UTC, tibetsprague approved these changes
i see you went ahead and cleaned up a lot of code, thanks :)

2022-02-15 03:15 UTC, merged