[EVO-972] Add Translations
Hylozoic/hylo-evo pull request #1385
Opened 2022-12-06 04:38 UTC by Sofacosta

2022-12-06 04:44 UTC, lorenjohnson reviewed
Looking good✨

Remind me that we should talk about `Suspense`. You won't have any trouble in dev, but we may need to merge a related branch I have which supports it server-side (due to out server-side rendering setup). No stress if you don't follow entirely, just flagging this for now.

2022-12-29 16:46 UTC, lorenjohnson commented
Here is the branch we'll need so that Suspense works once this is deployed to staging or production: https://github.com/Hylozoic/hylo-evo/pull/1322

2023-01-09 03:02 UTC, tibetsprague reviewed
just starting to go through but have some comments to start with

2023-01-09 03:02 UTC, tibetsprague commented on public/locales/es/translation.json
> +  "What I'm learning": "",
lets just pick the uppercase version above and use that one

2023-01-09 03:02 UTC, tibetsprague commented on public/locales/es/translation.json
> +  "You have unsaved changes. Are you sure you want to leave?": "",
we dont need these two version of the same things, lets use the one with the comma

2023-01-09 18:17 UTC, Sofacosta commented on public/locales/es/translation.json
> +  "1 Group is a part of {{group.name}}": "",
No, this is handled in the code

2023-01-09 18:20 UTC, Sofacosta commented on public/locales/es/translation.json
> +  "<span styleName='bold'>You</span> contributed {{amount}} to \"{{text}}\"": "",
The HTML is part of the formatting and there's no other way to translate the string without losing the context of the complete sentence

2023-01-09 18:22 UTC, Sofacosta commented on public/locales/es/translation.json
> +  "<strong>Custom View #{{count}}</strong>{{name}}": "",
The HTML is part of the formatting and there's no other way to translate the string without losing the context of the complete sentence

2023-01-09 18:27 UTC, Sofacosta commented on public/locales/es/translation.json
> +  "External link": "",
No, the context is different in the different places they are used.

2023-01-09 18:27 UTC, Sofacosta commented on public/locales/es/translation.json
> +  "Go back": "",
Yes, the context is different in the different places they are used.

2023-01-09 18:32 UTC, Sofacosta commented on public/locales/es/translation.json
> +  "Signup or Login to connect with": "",
Yes

2023-01-09 18:37 UTC, Sofacosta commented on public/locales/es/translation.json
> +  "This means that all members of the {{groupCount}} groups selected will receive instant email and push notifications about this Post. (This feature is available to moderators only.": "",
Yes

2023-01-09 18:41 UTC, Sofacosta commented on public/locales/es/translation.json
> +  "To view all groups you are a part of go to your": "",
No, the translation had to be split because we don't use a translation key system, which would enable us to make this translation without splitting.

2023-01-09 18:41 UTC, Sofacosta commented on public/locales/es/translation.json
> +  "To": "",
This is an automatically generated file, so comments are not possible. An unfortunate side effect of not using translation keys, is that context is lost and using duplicate translations like this becomes risky and difficult to translate effectively.

2023-01-12 23:17 UTC, tibetsprague requested changes
amazing! so much work. there are some TODOs left here plus a few other requests and comments

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/GroupDetail/GroupDetail.js
> +          {group.prerequisiteGroups.length === 1 ? <h4>{group.name} is only accessible to members of {group.prerequisiteGroups.map(prereq => <span key={prereq.id}>{prereq.name}</span>)}</h4> : <h4>{t
TODO

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/GroupDetail/GroupDetail.js
> +              To join {group.name} <Link to={fullPage ? groupUrl(prereq.slug) : groupDetailUrl(prereq.slug, routeParams)} styleName='g.prereqVisitLink'>visit {prereq.name}</Link> and become a member
TODO

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/GroupSettings/CustomViewsTab/CustomViewsTab.js
> +                            <span>{postType.charAt(0).toUpperCase() + postType.slice(1)}s</span> {/* TODO: Handle this translation */}
TODO

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/GroupSettings/ImportExportSettingsTab/ImportExportSettingsTab.js
> +        <div styleName='title'>{this.props.t('Import Posts by CSV')}</div>
put t into a const

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/GroupSettings/InviteSettingsTab/InviteSettingsTab.js
> +                Anyone can join <span style={{ fontWeight: 'bold' }}>{group.name}</span> with this link{inviteLink && '. Click or press on it to copy it'}: {/* TODO: Handle this translation */}
TODO

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/GroupSettings/PrivacySettingsTab/PrivacySettingsTab.js
>              <strong styleName='styles.warning'>Warning:</strong> If you select a prerequisite group that has a visibility setting of
TODO

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/GroupSettings/RelatedGroupsTab/RelatedGroupsTab.js
> +        if (window.confirm(`Are you sure you want to ${GROUP_RELATIONSHIP_TYPE.ParentToChild ? 'remove' : 'leave'} ${this.props.group.name}?`)) { // TODO: Handle this translation
TODO

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/MemberProfile/MemberProfile.js
> +    blockConfirmMessage: `Are you sure you want to block this member?
TODO?

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/NonAuthLayoutRouter/util.js
> +  const noPasswordMatch = error.match(/password account not found. available: \[(.*)\]/) // TODO: Handle this translation
TODO

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/PostDetail/Comments/Comment/Comment.connector.js
> +  const deleteCommentWithConfirm = (commentId) => window.confirm('Are you sure you want to delete this comment?') && // TODO: Handle this translation
TODO

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/PostDetail/Comments/Comment/Comment.connector.js
> +  const removeCommentWithConfirm = (commentId) => window.confirm('Are you sure you want to remove this comment?') && // TODO: Handle this translation
TODO

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/PostDetail/Comments/Comment/Comment.js
> +export class Comment extends Component { /* TODO: Handle translations in this file */
TODO

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/PublicLayoutRouter/PublicLayoutRouter.js
> +import cx from 'classnames'
we did you move this down? its not alphabetical anymore

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/UserSettings/AccountSettingsTab/AccountSettingsTab.js
> +      <div styleName='title'>{this.props.t('Update Account')}</div>
put t into a const

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/UserSettings/AccountSettingsTab/AccountSettingsTab.js
> +              <li>{this.props.t('You won\'t be able to use Hylo unless you log back in')}</li>
put t into a const

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/UserSettings/AccountSettingsTab/AccountSettingsTab.js
> +            This action is <strong style={{ color: 'red' }}>NOT</strong> reversible {/* TODO: Handle this translation */}
TODO

2023-01-12 23:17 UTC, tibetsprague commented on src/routes/UserSettings/EditProfileTab/EditProfileTab.js
> +      <SettingsControl label={this.props.t('Tagline')} onChange={this.updateSetting('tagline')} value={tagline} maxLength={60} />
put t into a const

2023-01-13 05:34 UTC, lorenjohnson commented on public/locales/es/translation.json
> +  "useLayoutFlags must be used within a LayoutFlagsProvider": "",
This doesn't need to be translated IMHO

2023-03-20 20:25 UTC, thomasgwatson commented
Merged dev back into this branch and included a bunch of tweaks.

I have a list of components that were impacted by merge-conflicts and I'm going to try validate that each is now working as intended. Basically any front-end work done between now and December might be a bit off.

2023-03-24 23:59 UTC, thomasgwatson commented
Ok....

Draft es translations are now available.

I would like to work towards merging this branch into dev. I've scanned over the app and different components multiple times but we'll still probably want to test it in staging anyway. 

After that, we can then progress with work on adding a way to select languages.

2023-05-03 21:43 UTC, tibetsprague commented
/Users/tibet/Dev/hylo/hylo-evo/src/routes/NonAuthLayoutRouter/util.js has a translation TODO in it

2023-05-03 21:49 UTC, tibetsprague commented
Found bug: try going to group explorer and selecting Farms and then clicking on the Filters - it crashes saying Error: Rendered more hooks than during the previous render.

2023-05-04 05:32 UTC, tibetsprague commented
Bug: the Create Role button says t('Create Role')

2023-05-08 22:46 UTC, thomasgwatson commented
> 

This function relies on an english language string to detect if its an error or not... that's not going to be reliable going forward. I am leaving this as a todo for #1498

2023-05-11 20:49 UTC, tibetsprague commented
Found a little broken spot: go to a User's profile and change the dropdown from Overview to Posts and it says "{{name}}s posts". (Also the posts don't load but thats a separate bug which i have filed)

2023-05-11 20:53 UTC, tibetsprague commented
Mousing over the visibility setting icon for a group in the group about info on the group explorer is showing this partially translated text: "Público - Anyone can find and see this group"

2023-05-11 20:57 UTC, tibetsprague commented
On the notifications settings page the text On and Off is not translated, and neither are the tooltips when hovering over the On/Off buttons

2023-05-12 21:51 UTC, merged