476 fix creating empty comments
Hylozoic/hylo-evo pull request #725
Opened 2020-12-21 11:04 UTC by veselinn

Related to #476 

### Media

Screenshot | GIF Demo
--- | ---
<img width="384" alt="image" src="https://user-images.githubusercontent.com/1181957/102769149-eadf9080-438a-11eb-913c-686b17a38365.png"> | ![2020-12-21_empty-comment-error](https://user-images.githubusercontent.com/1181957/102769160-efa44480-438a-11eb-9d46-5512c0e1c9db.gif)

### Explanations

Adds a simple check if the content of the comment is empty. Displays an inline error if an empty comment is tried to be posted.
:warning: Please let me know if the error message is alright. Dunno how user friendly it is.

---

:rotating_light: This solution doesn't permit posting a comment with only an attachment. Attaching an attachment and pressing _enter_ triggers the empty comment error. This is because the attachment is at one level higher - in the [`CommentForm`](https://github.com/Hylozoic/hylo-evo/blob/15adf47506fa9604d5ef190678980aef2244f3d5/src/routes/PostDetail/Comments/CommentForm/CommentForm.js#L38-L53), while the fix is introduced in the `HyloEditor`.

**Q:** Why not introduce the fix in the `CommentsFrom#save`?
**A:** In the `save` we have the html content, an empty content is in the form of `<p></p>`. Hardcoding an empty check against `<p></p>` looks like a bad idea to me.(I have no good argument here, let me know if this approach should be pursued).

Let me know if this is a showstopper. Thanks for the opportunity!

2020-12-28 20:42 UTC, tibetsprague requested changes
Thanks for this! I would actually say that we don't need an error message at all, since most people wouldn't expect to be able to post an empty comment. Also I think it is a dealbreaker to not be able to post a comment with just an attachement, that feels important to me

2021-01-04 13:34 UTC, veselinn commented
Happy new year! :sparkler: Thanks for the feedback!

 * Removed the error message.
 * Allows comments with no text but attachments.
 * Does not allow comment with no text and no attachments.
 
 Please, let me know if the solution is good enough. This was the best compromise I landed on.

2021-01-11 19:30 UTC, tibetsprague requested changes
this looks good! only little change id ask for is to trim the text so to also reject comments that are just whitespace

2021-01-12 12:07 UTC, veselinn commented
Great call! Added a check for trimmed text.

2021-01-13 06:07 UTC, tibetsprague approved these changes

2021-01-13 06:07 UTC, merged